CC=gcc
CFLAGS= -masm=intel 
LDFLAGS=
SOURCES=
OBJECTS= -o
B_FILES=bootLoader.bin kernelLoader.bin kernel.bin
LINKED=kernel_linked
OS=os.bin

all: OS_3

bootLoader.bin: bootLoader.asm
	nasm -f bin -o bootLoader.bin bootLoader.asm

kernelLoader.bin: kernelLoader.asm
	nasm -f bin -o kernelLoader.bin kernelLoader.asm

kernel.o: kernel.c
	$(CC) $(CFLAGS) -o kernel.o kernel.c


OS_1: bootLoader.bin 
	cat bootLoader.bin > os.bin
OS_2: OS_1 kernelLoader.bin $(OS)
	cat kernelLoader.bin >> os.bin
OS_3: OS_2 kernel.o $(OS)
	cat kernel.o >> os.bin

clean:
	rm *.bin *.o 
